# Generated by Django 5.1.7 on 2025-03-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="done",
            field=models.BooleanField(default=False),
        ),
    ]
